name: wirc_2025
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  equatable:
  path_provider:
  shared_preferences:
  package_info_plus:
  http:
  flutter_mjpeg:
  
  # # For test.
  # camera:
  # video_player:
  # flutter_hooks: # Used in flutter_mjpeg.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/